services:
  - type: web
    name: protronix-quote-generator
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn quote_generator.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false 