# Generated by Django 5.1.6 on 2025-02-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly_quantity', models.IntegerField(default=1)),
                ('total_basic_material_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material_overhead', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('warranty_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material_cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_moq_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('c_of_c_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tooling_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('customer_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_per_assembly', models.IntegerField()),
                ('units', models.CharField(default='EA', max_length=10)),
                ('quantity_required', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('extended_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moq', models.IntegerField()),
                ('excess_moq_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=100)),
                ('stock_qty', models.CharField(blank=True, max_length=50, null=True)),
                ('date_checked', models.DateField()),
                ('lead_time_days', models.IntegerField()),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('c_of_c_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tooling_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
        ),
    ]
