# Generated by Django 5.1.6 on 2025-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('quantity_required', models.IntegerField()),
                ('unit_cost', models.FloatField()),
                ('extended_cost', models.FloatField()),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
